{
 "title": "My Custom k8s Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Control Plan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Api Server",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"kube-system\",pod=\"kube-apiserver-minikube\",phase=\"Running\"} == 1"
      }
     ]
    },
    {
     "title": "Etcd Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"kube-system\",pod=\"etcd-minikube\",phase=\"Running\"} == 1"
      }
     ]
    },
    {
     "title": "Controller Manager Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"kube-system\",pod=\"kube-controller-manager-minikube\",phase=\"Running\"} == 1"
      }
     ]
    },
    {
     "title": "Scheduler Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"kube-system\",pod=\"kube-scheduler-minikube\",phase=\"Running\"} == 1"
      }
     ]
    },
    {
     "title": "Kube Proxy Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"kube-system\",pod=~\"kube-proxy-.*\",phase=\"Running\"} == 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "Count (kube_node_info)" }
     ]
    },
    {
     "title": "Healthy Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_node_status_condition{condition=\"Ready\",status=\"true\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total deployments",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_deployment_created)"
      }
     ]
    },
    {
     "title": "Healthy Deployments",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_deployment_status_condition{condition=\"Available\",status=\"true\"} == 1)"
      }
     ]
    },
    {
     "title": "Unhealthy Deployments",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_deployment_status_condition{condition=\"Available\",status=\"true\"} == 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "Count (kube_pod_created)" }
     ]
    },
    {
     "title": "Healthy Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_pod_status_phase {phase=\"Running\"} == 1 )"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_pod_status_phase{phase=\"Pending\"} == 1)"
      }
     ]
    },
    {
     "title": "ImagePullBackOff",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_pod_container_status_waiting_reason{reason=\"ImagePullBackOff\"} == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total DaemonSets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "Count (kube_daemonset_created)" }
     ]
    },
    {
     "title": "Healthy Daemonsets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_daemonset_status_number_ready == 1)"
      }
     ]
    },
    {
     "title": "Unhealthy DaemonSets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Count (kube_daemonset_status_number_unavailable == 1)"
      }
     ]
    }
   ]
  }
 ]
}