apiVersion: v1
kind: Service 
metadata:
  name: prometheus-nodeport
spec:
  type: NodePort
  ports: 
   - targetPort: 9090
     port: 9090
     nodePort: 30008 
  selector: 
    app: prometheus