pipeline {
    agent any

    stages {
    stage ("Hello"){
        steps {
            script {
                sh """
                echo "Hello World"
                ./var/jenkins_home/workspace/example/jenkins/bash/script.sh
                """
            }
        }
    }
    }
}