pipeline {
    agent any

    stages {
    stage ("Hello"){
        steps {
            script {
                sh """
                echo "Hello World"
                pwd
                ls
                bash -c "jenkins/bash/script.sh"
                """
            }
        }
    }
    }
}