{
 "title": "Openebs Pool dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": "label_values(openebs_pool_status, pool)"
   },
   {
    "name": "Replica",
    "query": "label_values(openebs_replica_status, vol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Status",
   "type": "singlestat",
   "description": "Status of pool (0, 1, 2, 3, 4, 5, 6) = {\"Offline\", \"Online\", \"Degraded\", \"Faulted\", \"Removed\", \"Unavail\", \"NoPoolsAvailable\"}",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_pool_status{pool=\"$Pool\"}"
    }
   ]
  },
  {
   "title": "Replica Rebuilding Status",
   "type": "singlestat",
   "description": "Status of rebuild on replica (0, 1, 2, 3, 4, 5, 6)= {\"INIT\", \"DONE\", \"SNAP REBUILD INPROGRESS\", \"ACTIVE DATASET REBUILD INPROGRESS\",       \"ERRORED\", \"FAILED\", \"UNKNOWN\"}",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_rebuild_status{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "Replica Total Rebuild Done Count",
   "type": "singlestat",
   "description": "Total no of rebuild performed",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_total_rebuild_done{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "Available Pool Size",
   "type": "singlestat",
   "description": "Available size of pool from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_available_size{name=\"$Pool\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Used Pool Size",
   "type": "singlestat",
   "description": "Used size of pool from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_used_size{name=\"$Pool\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Used Pool Size by replica",
   "type": "singlestat",
   "description": "Used size of pool by replica from zfs list",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_replica_used_size{name=\"$Pool/$Replica\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Replica Status",
   "type": "singlestat",
   "description": "Status of replica (0, 1, 2, 3) = {\"Offline\", \"Healthy\", \"Degraded\", \"Rebuilding\"}",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_replica_status{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "Replica Total Rebuild Failed Count",
   "type": "singlestat",
   "description": "Total no of rebuild performed which are failed",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_total_failed_rebuild{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "IO's count",
   "type": "graph",
   "description": "Read / Write / Sync IO's",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_count{pool=\"$Pool\", vol=\"$Replica\"}"
    },
    {
     "expr": "openebs_total_read_count{pool=\"$Pool\", vol=\"$Replica\"}"
    },
    {
     "expr": "openebs_sync_count{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Write latency on replica",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_write_latency{pool=\"$Pool\", vol=\"$Replica\"}[2m])/increase(openebs_write_block_count{pool=\"$Pool\", vol=\"$Replica\"}[2m])"
    },
    {
     "expr": "increase(openebs_read_latency{pool=\"$Pool\", vol=\"$Replica\"}[2m])/increase(openebs_read_block_count{pool=\"$Pool\", vol=\"$Replica\"}[2m])"
    },
    {
     "expr": "increase(openebs_sync_latency{pool=\"$Pool\", vol=\"$Replica\"}[2m])/increase(openebs_sync_count{pool=\"$Pool\", vol=\"$Replica\"}[2m])"
    }
   ]
  },
  {
   "title": "IO's in bytes",
   "type": "graph",
   "description": "Read / Write / Sync io's in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_bytes{pool=\"$Pool\", vol=\"$Replica\"}"
    },
    {
     "expr": "openebs_total_read_bytes{pool=\"$Pool\", vol=\"$Replica\"}"
    },
    {
     "expr": "openebs_rebuild_bytes{pool=\"$Pool\", vol=\"$Replica\"}"
    }
   ]
  }
 ]
}
{
 "title": "OpenEBS Volume Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OpenEBS",
    "label": "OpenEBS Volume",
    "query": "label_values(openebs_size_of_volume, openebs_pv)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Elapsed time since Volume was provisioned",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_uptime{job!=\"\", openebs_pv=~\"$OpenEBS\"}/60"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "description": "Capacity Used by the Volume",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_size_of_volume{openebs_pv=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_pv=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/openebs/chitrakala/master/OpenEBS%20logo/openebs%20logos-03.png\" alt=\"OpenEBS logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">OpenEBS</span>\n\n<p style=\"margin-top: 10px;\">You're monitoring OpenEBS Volumes using Prometheus. For more information, check out the <a href=\"http://openebs.io/\">OpenEBS</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects. If you would like to retain this volume monitoring data and much more, sign-up for <a href=\"http://mayaonline.io/\">MayaOnline</a> </p>"
   },
   "content": "<img src=\"https://raw.githubusercontent.com/openebs/chitrakala/master/OpenEBS%20logo/openebs%20logos-03.png\" alt=\"OpenEBS logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">OpenEBS</span>\n\n<p style=\"margin-top: 10px;\">You're monitoring OpenEBS Volumes using Prometheus. For more information, check out the <a href=\"http://openebs.io/\">OpenEBS</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects. If you would like to retain this volume monitoring data and much more, sign-up for <a href=\"http://mayaonline.io/\">MayaOnline</a> </p>"
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "IOPS",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_reads{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Reads}}"
    },
    {
     "expr": "increase(openebs_writes{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Writes}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_read_block_count{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{Read Throughput}}"
    },
    {
     "expr": "increase(openebs_write_block_count{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{Write Throughput}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((increase(openebs_read_time{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m]))/(increase(openebs_reads{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{Read Latency}}"
    },
    {
     "expr": "((increase(openebs_write_time{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m]))/(increase(openebs_writes{job!=\"\", openebs_pv=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{Write Latency}}"
    }
   ]
  }
 ]
}